#!/usr/bin/env bash

if [[ "$1" == "-q" ]] || [[ "$1" == "-Q" ]]; then
	QUICK="$1"
	MESSAGE=""
else
	MESSAGE="$1"
	QUICK="$2"
fi

if [[ -z "$MESSAGE" ]]; then
	MESSAGE="deployed on `date`"
fi

if [[ "$QUICK" == "-q" ]] || [[ "$QUICK" == "-Q" ]]; then
	echo "[info] running: activator stage"
	~/devSoft/play/activator-1.3.6-minimal/activator stage
else
	echo "[info] running: activator clean compile stage"
	~/devSoft/play/activator-1.3.6-minimal/activator clean compile stage
fi

echo "[info] running: git add . -A"
git add . -A

echo "[info] running: git commit -m \"$MESSAGE\""
git commit -m "$MESSAGE"

echo "[info] running: git push origin"
git push origin